import starByDex from "../data/pokemon/starByDex.json";

/**
 * Star ratings (1..7) for every species, and the posts it takes to beat an
 * encounter of that star in the forum game. Generated by scripts/gen-stars.mjs
 * from base stat totals plus the owner's fixed rules:
 *   6 star = pseudo-legendary class (Garchomp, Dragonite, ...): 12 posts
 *   7 star = legendaries, mythicals, Ultra Beasts, Paradox: 20 posts
 * 1..5 follow base stat total bands calibrated to the Safari default pools.
 *
 * The server mirrors these values in functions/src/index.ts (functions cannot
 * import from src); keep them in sync. The Safari Contest keeps its own
 * separate 1..5 posts-to-defeat scale (src/lib/safari.ts).
 */

export type EncounterStar = 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const STAR_POSTS_TO_BEAT: Record<EncounterStar, number> = {
  1: 2,
  2: 3,
  3: 5,
  4: 7,
  5: 9,
  6: 12,
  7: 20,
};

/**
 * Chance (percent) that an attempt to run away from a wild encounter succeeds,
 * by the enemy's star. Bosses and trainer-owned (non-catchable) Pokemon cannot
 * be fled; a failed attempt wastes the turn and the enemy still attacks.
 */
export const STAR_FLEE_CHANCE: Record<EncounterStar, number> = {
  1: 80,
  2: 70,
  3: 60,
  4: 50,
  5: 40,
  6: 30,
  7: 20,
};

/**
 * Flat damage an enemy of this star deals with one attack (one battle post).
 * The defender's max HP is level-based (see maxHpForLevel); its bar renders
 * with as many segments as its own star's posts-to-beat. The user's pokemon
 * always strikes first, so an enemy beaten this post never hits back. Admins
 * can override these per star (and the HP scaling) in Admin > Battle Costs;
 * a boss uses its species' star damage unless the host set a custom value.
 */
export const STAR_ATTACK_DAMAGE: Record<EncounterStar, number> = {
  1: 20,
  2: 30,
  3: 45,
  4: 60,
  5: 80,
  6: 100,
  7: 140,
};

/** Default level-based max HP scaling (admin-editable in Battle Costs). */
export const DEFAULT_HP_SCALING = { base: 100, low: 2, high: 4, split: 50 };

/** Max HP for a pokemon of this level under the given (or default) scaling. */
export function maxHpForLevel(
  level: number,
  hp: { base: number; low: number; high: number; split: number } = DEFAULT_HP_SCALING
): number {
  const lvl = Math.max(1, Math.min(100, Math.trunc(level) || 1));
  return hp.base + hp.low * (Math.min(lvl, hp.split) - 1) + hp.high * Math.max(0, lvl - hp.split);
}

/** Star rating for a national dex number (defaults to 3 for unknown). */
export function starForDex(idx: number | string): EncounterStar {
  const star = (starByDex as Record<string, number>)[String(Number(idx))];
  return (star && star >= 1 && star <= 7 ? star : 3) as EncounterStar;
}

/** Posts needed to beat an encounter of this star. */
export function postsToBeatStar(star: number): number {
  return STAR_POSTS_TO_BEAT[(star >= 1 && star <= 7 ? star : 3) as EncounterStar];
}

/** Flee success chance (percent) against an enemy of this star. */
export function fleeChanceForStar(star: number): number {
  return STAR_FLEE_CHANCE[(star >= 1 && star <= 7 ? star : 3) as EncounterStar];
}

/** Attack damage (percent of the defender's bar) an enemy of this star deals. */
export function attackDamageForStar(star: number): number {
  return STAR_ATTACK_DAMAGE[(star >= 1 && star <= 7 ? star : 3) as EncounterStar];
}
