import starByDex from "../data/pokemon/starByDex.json";

/**
 * Star ratings (1..7) for every species, and the posts it takes to beat an
 * encounter of that star in the forum game. Generated by scripts/gen-stars.mjs
 * from base stat totals plus the owner's fixed rules:
 *   6 star = pseudo-legendary class (Garchomp, Dragonite, ...): 8 posts
 *   7 star = legendaries, mythicals, Ultra Beasts, Paradox: 12 posts
 * 1..5 follow base stat total bands calibrated to the Safari default pools.
 *
 * The server mirrors these values in functions/src/index.ts (functions cannot
 * import from src); keep them in sync. The Safari Contest keeps its own
 * separate 1..5 posts-to-defeat scale (src/lib/safari.ts).
 */

export type EncounterStar = 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const STAR_POSTS_TO_BEAT: Record<EncounterStar, number> = {
  1: 3,
  2: 4,
  3: 5,
  4: 6,
  5: 7,
  6: 8,
  7: 12,
};

/** Star rating for a national dex number (defaults to 3 for unknown). */
export function starForDex(idx: number | string): EncounterStar {
  const star = (starByDex as Record<string, number>)[String(Number(idx))];
  return (star && star >= 1 && star <= 7 ? star : 3) as EncounterStar;
}

/** Posts needed to beat an encounter of this star. */
export function postsToBeatStar(star: number): number {
  return STAR_POSTS_TO_BEAT[(star >= 1 && star <= 7 ? star : 3) as EncounterStar];
}
