import rarityByItem from "../data/item/rarityByItem.json";

/**
 * Item obtainability rarity, mirroring the Pokemon star system
 * (src/lib/encounterStars.ts). A base tier per item ships in
 * src/data/item/rarityByItem.json (generated by scripts/gen-item-rarity.mjs);
 * admins retune individual items in `admin/item_rarity_overrides`.
 *
 *   0 Flavor      decorative dex item, not in the economy (no obtain expected)
 *   1 Common      base shop stock, always buyable for Snag Coins
 *   2 Uncommon    craft / trade / berry farm / recycle / mid-tier shop
 *   3 Rare        RNG only: tours roll, fishing, mystery box, daily-rare, casino
 *   4 Epic        mission / challenge / research reward, special shop
 *   5 Legendary   admin / event grant only, plot-unique
 */
export type ItemRarity = 0 | 1 | 2 | 3 | 4 | 5;

export const RARITY_LABELS: Record<ItemRarity, string> = {
  0: "Flavor",
  1: "Common",
  2: "Uncommon",
  3: "Rare",
  4: "Epic",
  5: "Legendary",
};

/** Tier accent colors (redesign palette; greens retired, cyan carries success). */
export const RARITY_COLORS: Record<ItemRarity, string> = {
  0: "#6f6a78",
  1: "#b6b1bc",
  2: "#12B7B6",
  3: "#4049C9",
  4: "#772976",
  5: "#FFD074",
};

/** How each tier is meant to be obtained (for the audit + UI copy). */
export const RARITY_OBTAIN: Record<ItemRarity, string> = {
  0: "Decorative, not obtainable by design",
  1: "Base shop stock",
  2: "Craft, trade, farm, recycle, or a mid-tier shop",
  3: "Rolled at Nature Tours, fishing, a mystery box, or a daily-rare pool",
  4: "A mission, challenge, or research reward",
  5: "Admin or event grant only",
};

/** Base obtainability tier for an item id (defaults to Uncommon if unknown). */
export function rarityForItem(itemId: string): ItemRarity {
  const r = (rarityByItem as Record<string, number>)[itemId];
  return (r === undefined ? 2 : (r as ItemRarity));
}

/** Base tier with an admin override doc (admin/item_rarity_overrides) applied. */
export function rarityWithOverride(
  itemId: string,
  overrides?: Record<string, number>
): ItemRarity {
  const o = overrides?.[itemId];
  if (typeof o === "number" && o >= 0 && o <= 5) return o as ItemRarity;
  return rarityForItem(itemId);
}
