/**
 * Baked-in site identity used for SEO. These are the crawler-facing defaults:
 * crawlers cannot read Firestore, so anything a bot must see lives here (and
 * in index.html / scripts/gen-sitemap.mjs), not in the admin/seo doc. The
 * admin/seo doc only overrides the social share images and X handle at
 * runtime for real visitors.
 */
export const SITE_URL = "https://snagemguild.com";
export const SITE_NAME = "Snagem Guild";
export const TITLE_SUFFIX = " | Snagem Guild";

export const DEFAULT_DESCRIPTION =
  "Join the Snagem Guild, a free Pokemon roleplay community with custom story forums, missions, battles, and a living world of Shadow Pokemon. Start your journey.";

/** Default social share image, generated by scripts/gen-og-image.mjs. */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/og-image.png`;

/** Build an absolute URL for a site path. */
export function absoluteUrl(path: string): string {
  if (/^https?:\/\//.test(path)) return path;
  return `${SITE_URL}${path.startsWith("/") ? "" : "/"}${path}`;
}

/**
 * Append the brand suffix to a page name, keeping the full title at or under
 * 60 characters where possible. If the name alone is already 60+, it is used
 * as-is (truncated) rather than pushing the title far past the limit.
 */
export function withSuffix(name: string): string {
  const clean = name.trim();
  if (clean.toLowerCase().includes("snagem")) return clean;
  if (clean.length + TITLE_SUFFIX.length <= 60) return clean + TITLE_SUFFIX;
  return clean.length <= 60 ? clean : `${clean.slice(0, 57).trimEnd()}...`;
}
