import {  Text,  Box,  } from '@mantine/core';

//Minimum password requirements
export const requirements = [
    { re: /[0-9]/, label: 'Includes number' },
    { re: /[a-z]/, label: 'Includes lowercase letter' },
    { re: /[A-Z]/, label: 'Includes uppercase letter' },
    { re: /[$&+,:;=?@#|'<>.^*()%!-]/, label: 'Includes special symbol' },
  ];
  
  //Visual indication of password strength
  export  function PasswordRequirement({ meets, label }: { meets: boolean; label: string }) {
    return (
      <Text
        color={meets ? 'teal' : 'red'}
        sx={{ display: 'flex', alignItems: 'center' }}
        mt={7}
        size="sm"
      >
        {meets ? 'A' : 'X'} <Box ml={10}>{label}</Box>
      </Text>
    );
  }
  
  //Indicate rating of password strength
  export function getStrength(password: string) {
    let multiplier = password.length > 5 ? 0 : 1;
  
    requirements.forEach((requirement) => {
      if (!requirement.re.test(password)) {
        multiplier += 1;
      }
    });
  
    return Math.max(100 - (100 / (requirements.length + 1)) * multiplier, 10);
  }
  
  //Generate password for applicants
  export function generatePassword() {
    var length = 8,
        charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
        retVal = "";
    for (var i = 0, n = charset.length; i < length; ++i) {
        retVal += charset.charAt(Math.floor(Math.random() * n));
    }
    return retVal;
}

//List of users pre-approved
  export const Gusers:Array<string>=[
      "SubonicXP",
      "Reno Vantas",
      "Darksol88",
      "Espeon_Commander",
      "Royal Summe",
      "SwankDon",
      "Dante Yashi",
      "bloodshed2.0",
      "cannibalelves",
      "Wazi Kong",
      "Pelchik",
      "I Am DakeDesu",
      "Carrie The Ninja",
      "The Azure Maestro",
      "HammerofHam",
      "Al Eyan Hominid",
      "MisterCrimson",
      "Blue Bone Daddy",
      "Lord of the Vine",
      "Bokyaku Kuchiki",
      "Fancy Mr A",
      "Noire Silver",
      "DelsieD",
      "shadekitsune",
      "Toryuuku Shinjuku",
      "OfficerBooty",
      "KytanaTheThief",
      "Otternavy",
      "Tsuki the Fated Wind",
      "DignityPower",
      "Thard_Verad",
      "PNN - Carrie",
      "Brian_Link",
      "Kotsuko",
      "Cipher Head Django",
      "HunterMetroid64",
      "Not a Noise",
      "Sportsman189",
      "Magiking",
      "Midnight_Euphomy",
      "SpikeQB",
      "UBERSERKERMAN",
      "coolgriff14",
      "bloodysword4",
      "Sylar Ginyoku",
      "DragonYolk",
      "KisaRinny",
      "Kasumi of Vientown",
      "MoniqueBrie",
      "-l- JoltiBun -l-",
      "DeathDealervamp",
      "MurasakiTek",
      "Hauntedflames",
      "Pixelsylveon",
      "Steven Quartz Universee",
      "Local Imp",
      "Pale1Ryder",
      "BirdieAnn15",
      "Tainted Blonde",
      "Lyle Tsuyoshi",
      "Keiko Yurino",
      "Jay Angel Of Darkness",
      "a-girl-named-Angel",
      "DrachenKaiser2021",
      "Netherworld Overlord-Has",
      "DragonFang099",
      "KrystatheMewes",
      "glitchedmirrors",
      "vunqs",
      "Cecile Silverstone",
      "emensmansera",
      "manglewren",
      "A Scarecrow",
      "Arkelos",
      "CrystalizedMagic",
      "Mistress Dahlia",
      "Stardust Drifter",
      "NotAnUndercoverCop",
      "Koukaze",
      "kid_brown45",
      "Zoideu",
      "Valiant Fenris",
      "Michael Bladebreaker",
      "prinxe shadow",
      "Skulllily",
      "Ryssa Blackblood",
      "Fridurmus",
      "In the Garden of Monsters",
      "Grey Moonfang IV",
      "Jump Einatz",
      "Mournings of a Incubus",
      "forkcity",
      "Deviled Dregs",
      "DreamingInColour",
      "Isaac Hawking",
      "Heroyuy711",
      "Phoenix_Lord1010",
      "Matt The Mapler",
      "GC the Silence Slayer",
      "Umbykirb",
      "KoTci",
      "Sky~126",
      "YouCan-Not-Go",
      "PLATINUMGBASP",
      "Water demon Nathan",
      "Arthur_Hinton",
      "snagemalec",
      "Link3332",
      "Ambient ChrisC",
      "Katina Star",
      "W0F",
      "LinkwithZelda",
      "Mike_Version_1",
      "CirCusPhreak",
      "KatanaHunter",
      "Sage~of~Water",
      "Katsu Redmoon",
      "Iceman105",
      "Sammy-Rose",
      "Oni the crazy",
      "Otaku-RolePlay-Gamer",
      "Olimar7",
      "Lockichu22",
      "Luigi4ever1",
      "rico008",
      "Lucario Master",
      "Hadotaro",
      "Elphaba_The_Fallen_Angel",
      "Reutan",
      "RhymeJW",
      "Sage_Cinder",
      "MewtwoWarrior",
      "wings_of_Snagem",
      "LuckyDeviI",
      "GroudonSage",
      "YokoRoxMySox",
      "Falcoseymour",
      "Zykke",
      "Lord_Felix",
      "Azalin",
      "Linkx9999",
      "LanceDragorin",
      "Atlantis_Darts",
      "pokegod11(Cal)",
      "Team Snagem",
      "SGO",
      "Mark Brother of King",
      "Ama-Clutch",
      "Correst",
      "Ganonsdoom",
      "Arthmael",
      "Kawazoe Taiki",
      "Vulbreeon",
      "Arcanine_Hybrid",
      "Thursdays Noon",
      "Ms Edyn",
      "Blizzard120",
      "Requiem of Whyspers",
      "Trainer23667",
      "Dumb Furret",
      "TerashiLeonGoken",
      "Immortal Amaranth",
      "Crolley",
      "Aleissa",
      "Bloag",
      "auron legendary warrior",
      "kirby8cookie",
      "desertmonkeymanz",
      "[K.i.s.s.Y.o.u.r.W.h.a.t]",
      "Kyosuke Kusaragi",
      "lollyz",
      "Regal_Byrant",
      "*sonic",
      "Pyro_Onichan",
      "SlashJX",
      "HyrulianHistorian",
      "VampiricRogue",
      "pimp_a",
      "DarkSamus10",
      "Existence of Self",
      "Minamoto_Tennyo",
      "PokeGrove_Account",
      "megasonichobs",
      "Escobar Corbin",
      "Jin Kisuragi",
      "MiniSoul",
      "Ranpu Majjiku_NJ",
      "Kato Achendyn",
      "JaysonFour",
      "Kyosuke Kusaragi",
      "lollyz",
      "Regal_Byrant",
      "*sonic",
      "Pyro_Onichan",
      "SlashJX",
      "HyrulianHistorian",
      "VampiricRogue",
      "pimp_a",
      "DarkSamus10",
      "Existence of Self",
    ];